name: Development Workflow

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16.x, 18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # The eslint-plugin-import rules only seem to work if the project is built
      - name: Build project
        run: npm run build

      - name: Run linters
        run: npm run --workspaces lint

      - name: Run tests
        run: npm run --workspaces test
