name: Release

on:
  push:
    branches: [master]

jobs:
  release-please:
    name: Create Release
    timeout-minutes: 20
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

  npm-release:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    name: Publish to npm registry
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3.3.0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Prepare for publish
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SOPHONBOT }}
